### ISSUE TITLE
Add style support for LaTex picture fragments (when not using MathJax)

### ISSUE THREAD

**Issue by simurgh9** [gongzhitaao/orgcss#15]
I just wanted to suggest the addition of something like this in [org.css](https://github.com/gongzhitaao/orgcss/blob/master/src/css/org.css),

```css
.figure p { text-align: center; }
.org-svg { width: auto; vertical-align:-3%; }
```
This centres the LaTex picture fragments better when not using MathJax (one might not want to use MathJax to support an arbitrary LaTex package). Here is a before and after,

**Before:**
![before](https://user-images.githubusercontent.com/43047754/85242724-6d4fbd80-b405-11ea-8658-07642215373d.png)
**After:**
![after](https://user-images.githubusercontent.com/43047754/85242735-73459e80-b405-11ea-9dbb-52c1ba0c6b68.png)
